# I use Travis CI to build the html documentation using a perl script.
# The build process proceeds in three steps:
# 1) Checkout the komments branch with the perl script kpp.pl
# 2) Build the html documentation using perl kpp.pl <filename>
#    using documentation.m from the master branch.
# 3) Push the html documentation to the gh-pages branch.
language: perl
branches:
  only:
  - master
env:
  global:
  secure: "3gORt1QgqZLtVwDZVzhj1Wx6pxKrbHnmPtxxCmSNhO13GJDp1xSYzPg1sHxaxY3qWKUBP4TOuMCqxRJyPKM99FjQ4k1AULqz5naiKG7+SkjsCJhDPHSox5cGyued9joOKmPlP43pPRhUr9tAxJX6LLQQlfuBTvAAMKs06dleFX4z/Fn4CXjwPVMGXR97YQORV618TZqblHw1RvXAsMoQZqk/Z9P/OZ/49CsL05rXRvsOaEDn9/G+AFoDFj3wyxt3wqFecuyOnR0mA5jeiP/SrQwIaiJDPkY5vZCCO0HQvN7Mj4nvMOygDCHx6Uzln6lcqEY0lYH0ZBMt1874SopCghmgRyVpk2YfwInhPi3H+XGJfnBcVMy7MHfw25SuCHVR40oFWeQJz05B7fVjX7eZBiapENPB7xJ0DwMRwWY+52t5c27GC95MoGCzqCOK4GcpaGry2KSwc5z6qMcbHSTAULW01D0UFiGZh3yCTRKyFCQj4YjOXZc5gj4KDX/gRjl2fSaswXzBhiGdDS+tDuz9ZgYk9MQfMX5Sbuo4UP6KdzcQlZLwELh3fyQfwEHJD6gyG6L7xeGUDYRSRo8we1iW86WZKzWYxQmJK4aeY9gUnzwek4JgHoHsPJIaIqvl00DtDsiPUWwND9eVsuLI3VvPRm11ghCEAbl+JLpkEINDKMk="
sudo: required
install:
- cd ~
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git komments
- cd komments
- git checkout komments
- git pull origin komments
script:
- cd ${TRAVIS_BUILD_DIR}
- perl ~/komments/kpp.pl documentation.m
- zip acty-sandbox.zip *.m *.html
after_success:
- cd ~
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- cd gh-pages
- git config user.name "Jan Tilly"
- git config user.email "jantilly@gmail.com"
- git checkout gh-pages
- git pull origin gh-pages
- mv ${TRAVIS_BUILD_DIR}/documentation.m.html .
- mv ${TRAVIS_BUILD_DIR}/acty-sandbox.zip .
- git add *.html *.zip
- git commit -m "automatic travis update"
- git push origin gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
