language: perl
branches:
  only:
  - master
sudo: required
env:
  global:
    secure: t6TXSXXxd7H51B1nTi/2M4v+lQdQb7O3LTnDp0aJm5JSrELYSINp1RvAXuZg205jwhjrfu8zHuYsMhxVlBmgLYeYQjkMMPUFB4VwJ7ZYMhBsreUnrQ0vEu5JfOtXFpBT9tbJ05m+vq+0H0k0ewHaCyHlPUP0crEamMPBz0qRqsJfxQmT8r/ejHrQK/tytDJhccsV2uRBSPPzqOlDj8A+H38RpvPLC1K3H5fTeAyy6mGb39RkdG6cq40yHhKF8zknstcrNNlFJmTD/nr9ugEuOPxK2d5hrh/QVq7wFDhDesPI/pRXoPa/1lYqYTobhtjeIihRBm4dfKM/9AYpiJFSUE+AHho9CFI4lbFhF7OKNqJ3ET1hk+3Fe3a53ZeEwcVoz3JADjbTCoazbKocDK3kjRelk6FCO4IoiBb6rrVinDa9X0td0FTHQ6zSgqg7CEtot7HlO9bfo6hEysfGCOT//61n9Nkdc3HsFWgno5ZyJDY2d6XAVED7quq+0lVdmgHrFxB3it8BNnstN5qkX2Gwpu0d31pIyR/CqEpRUPR2O+X7C2O/z4SDllWZblx0MPdtHzPnkTU6c/1uq3I6d1S065SEYOMnlheBiI0TEchF2AsI+7Z2Nb50iBKzpF4VsxTLtzZKxJKF1LaW3EVHwrmRxBH3rOeDvyzm1uD/6WZCX10=
install:
- cd ~
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git komments
- cd komments
- git checkout komments
- git pull origin komments
script:
- cd ${TRAVIS_BUILD_DIR}
- perl ~/komments/kpp.pl documentation.m
- zip acty-sandbox.zip *.m *.html
after_success:
- cd ~
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- cd gh-pages
- git config user.name "Jan Tilly"
- git config user.email "jantilly@gmail.com"
- git checkout gh-pages
- git pull origin gh-pages
- mv ${TRAVIS_BUILD_DIR}/documentation.m.html .
- mv ${TRAVIS_BUILD_DIR}/acty-sandbox.zip .
- git add *.html *.zip
- git commit -m "automatic travis update"
- git push origin gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
